In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data\\vacancies_with_tags.csv', index_col= False)

In [3]:
np.random.seed(42)
random_sample = df.sample(100)

In [4]:
random_sample.to_csv('100_random_vacancies.csv', index = False)

In [3]:
df.head()

,Id,Name,Description,Professional_Role_Id,Professional_Role
0,129039824,Специалист технической поддержки,<p>Ищем специалистов <strong>БЕЗ ОПЫТА</strong...,121,Специалист технической поддержки
1,129043584,3D-визуализатор,<strong>Обязанности:</strong> <ul> <li>Подгото...,34,"Дизайнер, художник"
2,128944004,Главный разработчик Python,<p><strong>Кто нам нужен:</strong><br />Опытны...,96,"Программист, разработчик"
3,128021606,GenAI Product Analyst,<p><strong>ORO</strong> — Агентство маркетинго...,150,Бизнес-аналитик
4,128984804,Системный аналитик (ML),<p>В Центр развития Департамента информационны...,148,Системный аналитик

In [4]:
df.shape

(12106, 5)

In [6]:
df.Description.describe()

count                                                 12106
unique                                                10205
top       <p>Ищем специалистов <strong>БЕЗ ОПЫТА</strong...
freq                                                    224
Name: Description, dtype: object

In [7]:
filtered_df = df.drop_duplicates('Description')

In [8]:
filtered_df

,Id,Name,Description,Professional_Role_Id,Professional_Role
0,129039824,Специалист технической поддержки,<p>Ищем специалистов <strong>БЕЗ ОПЫТА</strong...,121,Специалист технической поддержки
1,129043584,3D-визуализатор,<strong>Обязанности:</strong> <ul> <li>Подгото...,34,"Дизайнер, художник"
2,128944004,Главный разработчик Python,<p><strong>Кто нам нужен:</strong><br />Опытны...,96,"Программист, разработчик"
3,128021606,GenAI Product Analyst,<p><strong>ORO</strong> — Агентство маркетинго...,150,Бизнес-аналитик
4,128984804,Системный аналитик (ML),<p>В Центр развития Департамента информационны...,148,Системный аналитик
...,...,...,...,...,...
12101,129022583,Ведущий инженер технической поддержки,<p><strong>Обязанности:</strong></p> <ul> <li>...,121,Специалист технической поддержки
12102,127980331,Инженер-программист 1С,<p><strong>Требования:</strong></p> <ul> <li>о...,96,"Программист, разработчик"
12103,129135465,Frontend-разработчик в офис в Казани,<p>Мы занимаемся полезным делом - создаем геои...,96,"Программист, разработчик"
12104,128994769,Графический дизайнер (FMCG),<p>Привет!<br />Компания «Большой мир» — созда...,34,"Дизайнер, художник"
12105,128967604,Оператор ПК/Оператор базы данных 1С,<strong>Обязанности:</strong> <ul> <li>Занесен...,84,"Оператор ПК, оператор базы данных"

In [9]:
n_duplicates = df.shape[0] - filtered_df.shape[0]
print(f'There are {n_duplicates} duplicates in the dataset!!!')

There are 1901 duplicates in the dataset!!!

In [12]:
filtered_df.to_csv('filtered_vacancies.csv', index=False)